wildfly/boms

pom.xml
Hi, I've updated versions of Arquillian-core and its components. Some of them were really old.
=> Updated versions of Arquillian and its components

pom.xml
Drone to 2.0.1.Final
Shrinkwrap Resolver to 2.2.4
container adapter to 2.0.0.Final
=> Arquillian update

pom.xml
=> set all dependencies as provided

CONTRIBUTING.md, README.adoc, javaee7/pom.xml, javaee8/javaee8-with-tools/README.md, javaee8/javaee8-with-tools/pom.xml, javaee8/pom.xml, pom.xml
JIRA: https://issues.jboss.org/browse/WFLY-10301
=> WFLY-10301: Java EE 8 BOMs

javaee8/pom.xml
JIRA: https://issues.jboss.org/browse/WFLY-11044
=> WFLY-11044: syncs resteasy version with server

client/ejb-client/pom.xml, client/ejb-legacy-client/pom.xml, client/jaxws-client/pom.xml, client/jms-client/pom.xml, client/pom.xml, javaee8/pom.xml
JIRA: https://jira.jboss.org/browse/WFLY-11266
=> WFLY-11266: introducing jaxws client bom

pom.xml, quickstarts/pom.xml
Issue: https://issues.jboss.org/browse/WFLY-12103
=> [WFLY-12103] adds internal usage quickstarts bom

quickstarts/pom.xml
Issue: https://issues.jboss.org/browse/WFLY-12195
=> [WFLY-12195] Remove unused bouncycastle dependencies

quickstarts/pom.xml
Issue: https://issues.jboss.org/browse/WFLY-12197
=> [WFLY-12197] Remove redundant dependency management on Quickstarts BOM

quickstarts/pom.xml
Issue: https://issues.jboss.org/browse/WFLY-12198
=> [WFLY-12198] Remove unused dependency

pom.xml
Issue: https://issues.jboss.org/browse/WFLY-12199
=> [WFLY-12199] Remove quickstarts module from parent

client/jaxws-client/pom.xml
Issue: https://issues.jboss.org/browse/WFLY-12253
=> [WFLY-12253] add javax.annotations replacement to JAXWS-Client BOM

pom.xml
Issue: https://issues.jboss.org/browse/WFLY-12288
=> [WFLY-12288] Re-add jboss public maven repo

javaee8/pom.xml
Issue: https://issues.jboss.org/browse/WFLY-12409
=> [WFLY-12409] include spec APIs directly from server dep mngmnt

client/ejb-client/pom.xml, client/ejb-legacy-client/pom.xml, javaee8/pom.xml
Issue: https://issues.jboss.org/browse/WFLY-12490
=> [WFLY-12490] Propagating changes from WFLY-12460 and WFLY-12418

pom.xml
Issue: https://issues.jboss.org/browse/WFLY-12494
=> [WFLY-12494] add product maven repository

client/jms-client/pom.xml, javaee8/pom.xml
Issue: https://issues.jboss.org/browse/WFLY-12490
=> WFLY-12490 pt2

client/ejb-client/pom.xml, javaee8/pom.xml
Issue: https://issues.jboss.org/browse/WFLY-12490
=> [WFLY-12490] update javax transitive artifacts exclusions

javaee8/pom.xml
Issue: https://issues.jboss.org/browse/WFLY-12490
=> [WFLY-12490] Upgrade jboss-saaj-api and saaj-impl from 1.3 to 1.4

jakartaee8/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-12893
=> [WFLY-12893] adding commons-logging to jakarta ee8 bom

client/ejb-client/pom.xml, client/ejb-legacy-client/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-12916
=> [WFLY-12916] EJB Client BOM builders optimization

.gitignore, jakartaee8/jakartaee8-with-tools/pom.xml, jakartaee8/pom.xml
Issue: https://issues.jboss.org/browse/WFLY-12973
=> WFLY-12973 add micro profile artifacts to BOMs

client/jms-client/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-12917
=> [WFLY-12917] JMS Client BOM builder optimization

jakartaee8/pom.xml, microprofile/pom.xml, pom.xml
Issue: https://issues.redhat.com/browse/WFLY-13208
Branch: master
=> [WFLY-13208] move mp artifacts to a new microprofile bom

microprofile/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-13208
Branch: master
=> [WFLY-13208] update MP BOM version

microprofile/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-13248
Branch: master
=> [WFLY-13248] Add Jakarta APIs that are included in MicroProfile to MicroProfile BOM

jakartaee8/jakartaee8-with-tools/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-13251
Branch: 19.0.x
=> [WFLY-13251] adds wildfly arquillian commons to *-with-tools BOMs

README.adoc
Issue: https://issues.redhat.com/browse/WFLY-13506
=> [WFLY-13506] adds mp bom to root README.adoc

.github/workflows/ci.yml
Signed-off-by: Ken Wills <kwills@redhat.com>
=> Only run CI on master

jakartaee8/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-13893
=> [WFLY-13893] manually manage version of ispn directory provider

jakartaee8/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-13785
=> [WFLY-13785] add server managed jackson-datatype-* to jakarta ee8 bom

pom.xml
Issue: https://issues.redhat.com/browse/WFLY-13914
=> [WFLY-13914] add maven repos to boms

microprofile/pom.xml
https://issues.redhat.com/browse/WFLY-13640
=> [WFLY-13640] Reactive Messaging and Kafka Client dependencies

jakartaee8/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-14922
=> [WFLY-14922] remove picketlink

microprofile/pom.xml
https://issues.redhat.com/browse/WFLY-14932 / https://github.com/wildfly/wildfly/pull/14619
=> [WFLY-14932] Add the SmallRye Reactive Messaging Kafka User API

jakartaee8/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-15314
=> [WFLY-15314] Remove JBoss Negotiation

pom.xml
Issue: https://issues.redhat.com/browse/WFLY-15500
=> [WFLY-15500] move to BOM Builder plugin 2.0.2.Final

jakartaee8/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-15788
=> [WFLY-15788] remove no longer supported legacy security artifacts

jakartaee8/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-16091
=> [WFLY-16091] remove picketbox-commons from jakarta ee8 bom

client/jms-client/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-16090
=> [WFLY-16090] replace netty-all on jms client bom

.github/workflows/ci.yml
Adds jobs for also testing build with dependencies, i.e. builds WildFly main branch and then builds BOMs with the version of WildFly built, among other improvements, such as multi OS and JDK.
=> GitHub Actions Improvements

README.adoc, client/ejb-client/pom.xml, client/ejb-legacy-client/pom.xml, client/jaxws-client/pom.xml, client/jms-client/pom.xml, ee/ee-with-tools/pom.xml, ee/pom.xml, microprofile/pom.xml, pom.xml
Issues: https://issues.redhat.com/browse/WFLY-16707, https://issues.redhat.com/browse/WFLY-16780
Please do not merge, WIP!
=> [WFLY-16707][WFLY-16780] Jakarta EE 10 BOMs 

client/ejb-client/pom.xml, client/ejb-legacy-client/pom.xml, client/jaxws-client/pom.xml, client/jms-client/pom.xml, client/pom.xml, jakartaee8/jakartaee8-with-tools/pom.xml, jakartaee8/pom.xml, microprofile/pom.xml, pom.xml
WildFly 26.1.2.Final is available on repository.jboss.org.
=> Move to WildFly 26.1.2.Final

client/jaxws-client/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-17706
=> [WFLY-17706] adds jakarta xml ws api to jaxws-client bom

microprofile/pom.xml
https://issues.redhat.com/browse/WFLY-18049
=> WFLY-18049 Include microprofile-lra-api in the MicroProfile BOM

microprofile/pom.xml
https://issues.redhat.com/browse/WFLY-18286
=> WFLY-18286 BOM doesn't contain Opentelemetry API

microprofile/pom.xml
https://issues.redhat.com/browse/WFLY-18359
https://issues.redhat.com/browse/WFLY-18357
https://issues.redhat.com/browse/WFLY-18358
https://issues.redhat.com/browse/WFLY-18318
https://issues.redhat.com/browse/WFLY-18361
=> [WFLY-18359][WFLY-18357][WFLY-18358][WFLY-18318][WFLY-18361] Missing MP BOM Artifacts
